name: Codespaces environment
on:
  pull_request:
    paths:
      - '.devcontainer/**'
      - '.github/workflows/devcontainer.yml'
  push:
    branches: [main]
    paths:
      - '.devcontainer/**'
      - '.github/workflows/devcontainer.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          persist-credentials: false
      - name: Build environment and check tools
        uses: devcontainers/ci@513af61f4de4f75d37e4438f184ba4358f0fc1ca # v0.3
        with:
          push: never
          runCmd: |
            bash .devcontainer/verify-tools.sh
            shellcheck .devcontainer/*.sh
            bash .devcontainer/check-terraform.sh
